# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: boto3+s3://productionodoo12369/backup/simple
backup_email_from: 'False'
backup_email_to: 'False'
backup_image_version: latest
backup_tz: America/Lima
cidr_whitelist: null
domains_prod:
- hosts:
  - simple.algoritmia.ml
domains_test: []
gitlab_url: null
odoo_dbfilter: '%d'
odoo_initial_lang: es_PE
odoo_listdb: false
odoo_oci_image: null
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
- /web
- /website/info
postgres_dbname: prod
postgres_username: odoo
postgres_version: '13'
project_author: Algoritmia
project_license: BSL-1.0
project_name: myproject-odoo
smtp_canonical_default: null
smtp_canonical_domains: null
smtp_default_from: null
smtp_relay_host: null
smtp_relay_port: 587
smtp_relay_user: null
smtp_relay_version: '10'
